version: "3.8"

services:
    backend:
        build: .
        ports:
            - "3333:3333"
        env_file:
            - .env
        volumes:
            - .:/app
            - /app/node_modules
        # depends_on:
        #   - db

    # db:
    #   image: postgres:13
    #   environment:
    #     POSTGRES_USER: postgres
    #     POSTGRES_PASSWORD: postgres
    #     POSTGRES_DB: mydatabase
    #   volumes:
    #     - db-data:/var/lib/postgresql/data

volumes:
    db-data:
